# Generated by Django 3.2.25 on 2025-01-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_APP', '0002_auto_20250111_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assign',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='cc',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='file_upload',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='knowledge_base',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assign_ticket',
            field=models.CharField(default='Current User', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='company',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='service',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
