# Generated by Django 3.2.25 on 2025-01-27 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_APP', '0005_bde_calllater_closed_followup_interested_lead_notinterested_notresponse_product_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BDE',
        ),
        migrations.DeleteModel(
            name='Calllater',
        ),
        migrations.DeleteModel(
            name='closed',
        ),
        migrations.DeleteModel(
            name='Followup',
        ),
        migrations.DeleteModel(
            name='Interested',
        ),
        migrations.DeleteModel(
            name='lead',
        ),
        migrations.DeleteModel(
            name='Notinterested',
        ),
        migrations.DeleteModel(
            name='Notresponse',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
