# Generated by Django 3.2.25 on 2025-01-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_APP', '0007_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BDE',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('password', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calllater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_later', models.DateField()),
                ('reason', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='closed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=200, null=True)),
                ('product', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('offer', models.CharField(max_length=100)),
                ('installation_type', models.CharField(max_length=200)),
                ('installation_date', models.DateField()),
                ('duration_from', models.DateField()),
                ('duration_to', models.DateField()),
                ('payment_type', models.CharField(max_length=100)),
                ('payment', models.IntegerField()),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_follow_up', models.DateField()),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Interested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
                ('priority', models.CharField(max_length=250)),
                ('product_type', models.CharField(max_length=250)),
                ('demo_date', models.DateField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=60)),
                ('specialization', models.CharField(max_length=50)),
                ('assigned', models.CharField(default='assigned', max_length=50)),
                ('mode', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('zipcode', models.IntegerField()),
                ('clinic_name', models.CharField(max_length=100)),
                ('default_language', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=200)),
                ('status', models.CharField(default='Open', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Notinterested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_follow_up', models.DateField()),
                ('reason', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Notresponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_calling', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(max_length=50)),
                ('packages', models.TextField()),
            ],
        ),
    ]
