# Generated by Django 3.2.25 on 2025-01-31 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_APP', '0008_bde_calllater_closed_followup_interested_lead_notinterested_notresponse_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('Did', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Clinic_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CT', 'Chhattisgarh'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OR', 'Odisha'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TG', 'Telangana'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UT', 'Uttarakhand'), ('WB', 'West Bengal'), ('AN', 'Andaman and Nicobar Islands'), ('CH', 'Chandigarh'), ('DN', 'Dadra and Nagar Haveli and Daman and Diu'), ('DL', 'Delhi'), ('JK', 'Jammu and Kashmir'), ('LA', 'Ladakh'), ('LD', 'Lakshadweep'), ('PY', 'Puducherry')], max_length=20)),
                ('City', models.CharField(max_length=100)),
                ('call_status', models.CharField(max_length=100)),
                ('Age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
                ('priority', models.CharField(max_length=250)),
                ('demo_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('next_follow_up', models.DateField(blank=True, null=True)),
                ('product_type', models.CharField(max_length=200, null=True)),
                ('product', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('offer', models.CharField(blank=True, max_length=100, null=True)),
                ('installation_type', models.CharField(max_length=200)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('duration_from', models.DateField(blank=True, null=True)),
                ('duration_to', models.DateField(blank=True, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('payment', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=250)),
                ('next_calling', models.DateField(blank=True, null=True)),
                ('call_later', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(max_length=400)),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM_APP.doctor')),
            ],
        ),
        migrations.DeleteModel(
            name='Calllater',
        ),
        migrations.DeleteModel(
            name='closed',
        ),
        migrations.DeleteModel(
            name='Followup',
        ),
        migrations.DeleteModel(
            name='Interested',
        ),
        migrations.DeleteModel(
            name='Notinterested',
        ),
        migrations.DeleteModel(
            name='Notresponse',
        ),
        migrations.AddField(
            model_name='lead',
            name='doctors',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='CRM_APP.doctor'),
            preserve_default=False,
        ),
    ]
