# Generated by Django 5.1.3 on 2025-02-01 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_APP', '0009_auto_20250131_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='doctors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='CRM_APP.doctor'),
        ),
    ]
