# Generated by Django 5.1.3 on 2025-02-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_APP', '0010_alter_lead_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(max_length=200),
        ),
    ]
