# Generated by Django 5.1.3 on 2025-02-06 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_APP', '0011_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='doc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interaction', to='CRM_APP.doctor'),
        ),
    ]
